Repository Puzzlepart/prosjektportalen365, pull requests merged in 2022-03, with the labels that each got.

#653 Add 'Vis alle egenskaper' button with customizable panel (ProjectInformation)
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectInformation.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/types.ts
  SharePointFramework/ProjectWebParts/src/loc/en-us.js
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
Labels: enhancement, complexity: small, frontend

#655 Added modified to shared to show published in statusreport
  SharePointFramework/@Shared/src/models/StatusReport.ts
Labels: backend

#656 Feature/654 published date
  SharePointFramework/@Shared/src/models/StatusReport.ts
Labels: backend

#659 Support for {site} token for project tasks
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/config/serve.sample.json
  SharePointFramework/ProjectExtensions/src/models/ProjectTemplate.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectInformation/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectPhases/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/manifest.json
Labels: enhancement

#664 Bugfix/661 timeline top500
  .github/PULL_REQUEST_TEMPLATE.md
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
Labels: bug

#663 Dynamic welcomepage and ProjectPhases webpart improvements
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/ChangePhaseDialog.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/reducer.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/ProjectPhaseCallout/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/changePhase.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/changeWelcomePage.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/fetchData.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/getPhaseSitePages.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/types.ts
  SharePointFramework/ProjectWebParts/src/loc/en-us.js
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
Labels: complexity: medium, backend, frontend, customer funded

#665 Add possibility to "lock" project template configurations
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/ExtensionsSection.module.scss
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/types.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListContentSection/ListContentSection.module.scss
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListContentSection/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListContentSection/types.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/models/ProjectTemplate.ts
  SharePointFramework/ProjectExtensions/src/models/ProjectTemplateFile.ts
  SharePointFramework/ProjectExtensions/src/models/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/@BaseTask/IBaseTask.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/types.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PreTask/index.ts
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
  Templates/Portfolio/Objects/SiteFields/GtSecViewQuery.xml
Labels: enhancement, easy-task, complexity: small, frontend

#657 Show report published date with fallback to created
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.tsx
Labels: backend
