Repository Puzzlepart/prosjektportalen365, pull requests merged in 2022-10, with the labels that each got.

#782 Fixing CI build errors
  SharePointFramework/PortfolioExtensions/.vscode/settings.json
  SharePointFramework/PortfolioExtensions/package-lock.json
  SharePointFramework/PortfolioExtensions/package.json
  SharePointFramework/PortfolioExtensions/src/components/IdeaApprovalDialog/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/IdeaDialog/index.tsx
  SharePointFramework/PortfolioExtensions/src/extensions/ideaProcessing/index.ts
  SharePointFramework/PortfolioExtensions/src/extensions/ideaProjectData/index.tsx
  SharePointFramework/PortfolioExtensions/src/extensions/ideaRegistration/index.tsx
  SharePointFramework/PortfolioExtensions/src/helpers/isUserAuthorized.ts
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnContextMenu/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ShowHideColumnPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/filter.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/DetailsCallout/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/index.tsx
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/models/TimelineContentListModel.ts
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/index.tsx
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/index.ts
  SharePointFramework/ProjectExtensions/package-lock.json
  SharePointFramework/ProjectExtensions/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/Actions/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/SyncProjectModal/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/SyncProjectModal/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/context.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformation.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformationDataTransform.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/ProjectPhaseCallout/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/ListSection/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/RiskSection/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/MatrixRow/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/types.tsx
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectInformation/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectPhases/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/index.ts
Labels: bug, complexity: small, dependencies

#790 Script to fix/update aggregated webpart pages
  CHANGELOG.md
  Install/Scripts/PostInstallUpgrade.ps1
  Install/Scripts/PreInstallUpgrade.ps1
  Install/Scripts/UpdateAggregatedClientSidePages.ps1
  Install/Scripts/pnpFiles/UpdatedAggregatedClientSidePages.pnp
  Install/Scripts/pnpFiles/UpdatedAggregatedClientSidePages_mac.pnp
Labels: bug

#795 Using Panel to show project information in portfolio overview etc
  SharePointFramework/PortfolioWebParts/.vscode/settings.json
  SharePointFramework/PortfolioWebParts/config/config.json
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/IRenderItemColumnProps.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TitleColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/UserColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/SyncProjectModal/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformation.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformationDataFetch.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformationPanel/ProjectInformationTooltip.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectInformationPanel/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformationPanel/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformationTooltip/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformationTooltip/types.ts
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
  SharePointFramework/ProjectWebParts/src/data/index.ts
  SharePointFramework/ProjectWebParts/tsconfig.json
Labels: enhancement, complexity: medium, frontend

#802 Add predefined help content and support help content on portfolio level
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/config/serve.sample.json
  SharePointFramework/ProjectExtensions/src/components/HelpContent/HelpContentModal/HelpContentModal.module.scss
  SharePointFramework/ProjectExtensions/src/components/HelpContent/HelpContentModal/index.tsx
  SharePointFramework/ProjectExtensions/src/helpContent/index.tsx
  SharePointFramework/ProjectExtensions/src/helpContent/types.tsx
  SharePointFramework/ProjectExtensions/src/models/HelpContentModel.ts
  Templates/Portfolio/Objects/CustomActions.xml
  Templates/Portfolio/Objects/Lists/Hjelpeinnhold.xml
Labels: enhancement, complexity: small

#815 Group and categorize Project Timeline elements
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Commands/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/ProjectTimeline.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/Timeline.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/Timeline.overrides.css
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/context.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/useProjectTimeline.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/useProjectTimelineDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/index.tsx
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/ITimelineGroup.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/ITimelineItem.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/models/TimelineConfigurationListModel.ts
  SharePointFramework/PortfolioWebParts/src/models/TimelineContentListModel.ts
  SharePointFramework/PortfolioWebParts/src/models/index.ts
  SharePointFramework/PortfolioWebParts/tsconfig.json
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/ProjectTimeline.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/TimelineList/TimelineList.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/TimelineList/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/context.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/useProjectTimeline.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/useProjectTimelineDataFetch.ts
  SharePointFramework/ProjectWebParts/src/loc/en-us.js
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/manifest.json
Labels: enhancement, complexity: small, backend, frontend, customer funded

#821 Dont render projects as links (ProgramAdmin add project dialog)
  CHANGELOG.md
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ProjectTable/ProjectTable.module.scss
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ProjectTable/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/index.tsx
Labels: enhancement, complexity: small

#828 Show multi taxonomy terms as labels in 'ProjectInformation' webpart
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectProperties/ProjectProperty/ProjectProperty.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectProperties/ProjectProperty/index.tsx
Labels: enhancement, frontend, customer funded

#855 Add '? Hjelp tilgjengelig' button to existing projects #844
  .development-guide/.README
  .development-guide/README.md
  .github/workflows/ci-dev.yml
  Install/Install.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
Labels: installation
