Repository Puzzlepart/prosjektportalen365, pull requests merged in 2022-06, with the labels that each got.

#732 Field types not in sync with 'Prosjektinnholdskolonner' data
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/models/ProjectColumn.ts
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/IProjectContentColumn.ts
  Templates/Portfolio/Objects/ContentTypes/Prosjektinnholdskolonne.xml
  Templates/Portfolio/Objects/Lists/Prosjektinnholdskolonner.xml
Labels: complexity: small, backend

#737 736 sync error
  CHANGELOG.md
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/services/ProjectDataService/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/fetchData.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/getWelcomePage.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/types.ts
Labels: bug

#739 v1.6.0
  SharePointFramework/PortfolioWebParts/package.json
Labels: release-pr

#746 v1.6.1
  CHANGELOG.md
  Install/Scripts/PreInstallUpgrade.ps1
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/PortfolioWebParts/README.md
  SharePointFramework/PortfolioWebParts/config/package-solution.json
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/types.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/benefitsOverview/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/latestProjects/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioInsights/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioOverview/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/projectTimeline/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/resourceAllocation/manifest.json
  SharePointFramework/ProgramWebParts/config/package-solution.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/webparts/programAdministration/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programBenefits/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programDeliveries/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programProjectOverview/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programRiskOverview/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programStatus/manifest.json
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/manifest.json
  SharePointFramework/ProjectExtensions/config/package-solution.json
  SharePointFramework/ProjectExtensions/package-lock.json
  SharePointFramework/ProjectExtensions/package.json
  SharePointFramework/ProjectExtensions/src/projectSetup/manifest.json
  SharePointFramework/ProjectExtensions/src/projectUpgrade/manifest.json
  SharePointFramework/ProjectExtensions/src/templateSelector/manifest.json
  SharePointFramework/ProjectWebParts/config/package-solution.json
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/ProjectWebParts/src/webparts/projectInformation/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectPhases/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/riskMatrix/manifest.json
  dev/.README
  package-lock.json
  package.json
Labels: release-pr
