Repository Puzzlepart/prosjektportalen365, pull requests merged in 2022-05, with the labels that each got.

#698 Timeline configuration, timeline rework + support for projectdeliveries
  CHANGELOG.md
  Install/Scripts/PostInstallUpgrade.ps1
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/DetailsCallout/DetailsCallout.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/DetailsCallout/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/Timeline.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/ITimelineItem.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/models/ProjectListModel.ts
  SharePointFramework/PortfolioWebParts/src/models/TimelineContentListModel.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectTimeline/manifest.json
  SharePointFramework/ProgramWebParts/config/serve.sample.json
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/ProjectWebParts/src/loc/en-us.js
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectTimeline/manifest.json
  Templates/Portfolio/Objects/ClientSidePages/Konfigurasjon.xml
  Templates/Portfolio/Objects/ClientSidePages/Prosjekttidslinje.xml
  Templates/Portfolio/Objects/ContentTypes/@.xml
  Templates/Portfolio/Objects/ContentTypes/Tidslinjeelement.xml
  Templates/Portfolio/Objects/ContentTypes/Tidslinjekonfigurasjonselement.xml
  Templates/Portfolio/Objects/Lists/@.xml
  Templates/Portfolio/Objects/Lists/Tidslinjeinnhold.xml
  Templates/Portfolio/Objects/Lists/Tidslinjekonfigurasjon.xml
  Templates/Portfolio/Objects/Lists/Tillatelseskonfigurasjon.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/GtElementType.xml
  Templates/Portfolio/Objects/SiteFields/GtHexColor.xml
  Templates/Portfolio/Objects/SiteFields/GtShowElementPortfolio.xml
  Templates/Portfolio/Objects/SiteFields/GtShowElementProgram.xml
  Templates/Portfolio/Objects/SiteFields/GtSiteIdLookup.xml
  Templates/Portfolio/Objects/SiteFields/GtTimelineFilter.xml
  Templates/Portfolio/Objects/SiteFields/GtTimelineTypeLookup.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
Labels: enhancement, complexity: medium, backend, frontend

#708 Timeline deliveries portfolio ++
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/projectTimeline/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectTimeline/manifest.json
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/components/ProgramTimeline/ProgramTimeline.tsx
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/index.ts
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/manifest.json
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
Labels: enhancement, complexity: medium, backend

#712 Add improvements to document template selector
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/components/DocumentTemplateDialog/DocumentTemplateDialog.module.scss
  SharePointFramework/ProjectExtensions/src/components/DocumentTemplateDialog/SelectScreen/index.tsx
  SharePointFramework/ProjectExtensions/src/components/DocumentTemplateDialog/TargetFolderScreen/index.tsx
  SharePointFramework/ProjectExtensions/src/loc/nb-no.js
Labels: enhancement, complexity: small, frontend, customer funded

#710 Fix for GtResourceLoad list column
  .gitignore
  CHANGELOG.md
  Install/Scripts/PostInstallUpgrade.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  Templates/JsonTemplates/_JsonTemplateProgram.json
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: bug
