Repository Puzzlepart/prosjektportalen365, pull requests merged in 2022-12, with the labels that each got.

#911 Bundle 'Bygg & Anlegg' addon directly into 'Prosjektportalen365'
  CHANGELOG.md
  Templates/Content/Portfolio_content.no-NB/Portfolio_content.no-NB.xml
  Templates/Portfolio/Objects/ContentTypes/@.xml
  Templates/Portfolio/Objects/ContentTypes/BA/Prosjekt (Bygg og anlegg).xml
  Templates/Portfolio/Objects/ContentTypes/BA/Prosjektstatus (Bygg og anlegg).xml
  Templates/Portfolio/Objects/Lists/@.xml
  Templates/Portfolio/Objects/Lists/BA/Fasesjekkliste Anlegg.xml
  Templates/Portfolio/Objects/Lists/BA/Fasesjekkliste Bygg.xml
  Templates/Portfolio/Objects/Lists/BA/Planneroppgaver Anlegg.xml
  Templates/Portfolio/Objects/Lists/BA/Planneroppgaver Bygg.xml
  Templates/Portfolio/Objects/Lists/BA/Standarddokumenter Anlegg.xml
  Templates/Portfolio/Objects/Lists/BA/Standarddokumenter Bygg.xml
  Templates/Portfolio/Objects/Lists/Listeinnhold.xml
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
  Templates/Portfolio/Objects/Lists/Prosjektdata.xml
  Templates/Portfolio/Objects/Lists/Prosjekter.xml
  Templates/Portfolio/Objects/Lists/Prosjektkolonnekonfigurasjon.xml
  Templates/Portfolio/Objects/Lists/Prosjektkolonner.xml
  Templates/Portfolio/Objects/Lists/Prosjektstatus.xml
  Templates/Portfolio/Objects/Lists/Statusseksjoner.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAEndDateOriginal.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectEnv.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectEnvComment.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectInvestementPhase.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectPolitical.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectPoliticalComment.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectPoliticalLink.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectPrognosisThisYear.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectSHA.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectSHAComment.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectStatusCase.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectStatusCaseComment.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectSupport.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAProjectSupportComment.xml
  Templates/Portfolio/Objects/SiteFields/BA/GtBAStakeholderGroup.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
  Templates/Taxonomy/Taxonomy.xml
Labels: enhancement, complexity: medium, customer funded

#929 Fixed issues with trailing slash in URL when installing/upgrading
  Install/Install.ps1
  SharePointFramework/PortfolioExtensions/package-lock.json
  SharePointFramework/PortfolioExtensions/package.json
  Templates/package-lock.json
Labels: installation

#935 Add tag to deliveries elements on timeline
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/fetchData.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/fetchTimelineData.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/transformItems.ts
Labels: bug, enhancement
