Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-06, with the labels that each got.

#1158 Fjerne "newlines" fra sjekkliste, etiketter og vedlegg under Planner provisjonering
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
Labels: bug

#1169 Fikse bug hvor "Alle prosjekter" standard-vertikal ikke fungerte
  CHANGELOG.md
  SharePointFramework/.tasks/modifySolutionFiles.js
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ItemModal/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ShowHideColumnPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ListHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TitleColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListViews.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListState.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/DetailsCallout/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/itemRenderer.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocationDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioInsights/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioOverview/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/resourceAllocation/index.ts
Labels: bug

#1168 "Stemple" gjeldende versjon på prosjektet når det konfigureres
  .github/workflows/pr-package-spfx-dev.yml
  SharePointFramework/ProjectExtensions/src/components/@BaseDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/components/DocumentTemplateDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/components/ErrorDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/components/ProgressDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ContentConfigSection/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/index.tsx
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ApplyTemplate/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/Hooks/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/SetupProjectInformation/index.ts
  SharePointFramework/ProjectExtensions/src/templateSelector/index.tsx
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
  Templates/Portfolio/Objects/ContentTypes/BA/Prosjekt (Bygg og anlegg).xml
  Templates/Portfolio/Objects/ContentTypes/Prosjekt.xml
  Templates/Portfolio/Objects/Lists/Prosjekter.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/GtCurrentVersion.xml
  Templates/Portfolio/Objects/SiteFields/GtInstalledVersion.xml
  Templates/Portfolio/Resources.no-NB.resx
Labels: enhancement, backend

#1172 Fikset problem hvor prosjekttidslinje ikke returnerte tilhørende elementer for prosjekt
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/fetchTimelineData.ts
Labels: bug, complexity: small

#1174 Fikset sortering for valuta i Porteføljeoversikt
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/reducer.ts
Labels: bug, backend

#1177 Løser problemer med 1.9 CI som overstyrer 1.8.x-pakker
  Install/Build-Release.ps1
  SharePointFramework/.tasks/modifySolutionFiles.js
Labels: ci

#1178 Justeringer på bygging og CI
  .vscode/settings.json
  Install/Build-Release.ps1
  Install/Scripts/PreInstallUpgrade.ps1
  channels/$schema.json
  channels/main.json
  channels/test.json
Labels: ci, build and packaging

#1181 Håndtering av 'null'-verdi på datofelt ved eksport til Excel
  CHANGELOG.md
  SharePointFramework/@Shared/src/helpers/getDateValue.ts
  SharePointFramework/@Shared/src/services/ExcelExportService/index.ts
Labels: bug

#1173 Fiks for feil ved utlisting av alle prosjekter i et program
  CHANGELOG.md
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/useAddProjectDialog.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/Commands/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/data.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/useProgramAdministration.ts
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/webparts/baseProgramWebPart/index.ts
Labels: bug

#1190 Fiks for #1188
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/types.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
Labels: bug, priority: high, hotfix

#1187 Sjekker forrige versjon i UpgradeAllSitesToLatest.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
Labels: bug, installation

#1191 Full bredde som standard for matriser
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/webparts/opportunityMatrix/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/manifest.json
  SharePointFramework/ProjectWebParts/src/webparts/riskMatrix/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/riskMatrix/manifest.json
Labels: enhancement

#1189 Informasjon om valgte elementer for programadministrasjon og prosjektoppsett-dialog
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ListHeaderSearch/ListHeaderSearch.module.scss
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ListHeaderSearch/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ListHeaderSearch/types.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/useSelectionList.ts
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ContentConfigSection/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ContentConfigSection/useContentConfigSection.ts
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ContentConfigSection/useRowRenderer.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/useExtensionsSection.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ExtensionsSection/useRowRenderer.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListHeaderSearch/ListHeaderSearch.module.scss
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListHeaderSearch/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/ListHeaderSearch/types.ts
  SharePointFramework/ProjectExtensions/src/loc/myStrings.d.ts
  SharePointFramework/ProjectExtensions/src/loc/nb-no.js
Labels: enhancement
