Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-10, with the labels that each got.

#1275 Script for å legge til gruppen Porteføljeadministratorer på eksisterende prosjekter
  Install/Scripts/Ensure-AdminUsers.ps1
Labels: installation, customer funded

#1276 Assist 5153 2
  Install/Scripts/Ensure-AdminUsers.ps1
Labels: customer funded

#1280 Visuelt løft på paneler for redigering av visninger/kolonner (Porteføljeoversikt/Aggregerte)
  SharePointFramework/PortfolioWebParts/src/components/EditViewColumnsPanel/EditViewColumnsPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/EditViewColumnsPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/List/ItemColumn/ColumnDataTypeField/ColumnRenderField.module.scss
  SharePointFramework/PortfolioWebParts/src/components/List/ItemColumn/ColumnDataTypeField/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/List/ItemColumn/ColumnDataTypeField/types.ts
  SharePointFramework/PortfolioWebParts/src/components/List/ItemColumn/ColumnDataTypeField/useDataTypeDropdown.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/ColumnFormPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/ColumnFormPanelFooter/ColumnFormPanelFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/ColumnFormPanelFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ViewFormPanel/ViewFormPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ViewFormPanel/ViewFormPanelFooter/ViewFormPanelFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ViewFormPanel/ViewFormPanelFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ViewFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/ColumnFormPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/ColumnFormPanelFooter/ColumnFormPanelFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/ColumnFormPanelFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/ColumnVisibilityField/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/ColumnVisibilityField/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnFormPanel/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ViewFormPanel/ViewFormPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ViewFormPanel/ViewFormPanelFooter/ViewFormPanelFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ViewFormPanel/ViewFormPanelFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ViewFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/tsconfig.json
  SharePointFramework/shared-library/src/components/Autocomplete/Autocomplete.module.scss
  SharePointFramework/shared-library/src/components/Autocomplete/Autocomplete.tsx
  SharePointFramework/shared-library/src/components/ColumnSearchPropertyField/index.tsx
  SharePointFramework/shared-library/src/components/FieldContainer/FieldContainer.tsx
  SharePointFramework/shared-library/src/components/FormFieldContainer/FieldDescription/FieldDescription.module.scss
  SharePointFramework/shared-library/src/components/FormFieldContainer/FieldDescription/index.tsx
  SharePointFramework/shared-library/src/components/FormFieldContainer/FormFieldContainer.module.scss
  SharePointFramework/shared-library/src/components/FormFieldContainer/index.tsx
  SharePointFramework/shared-library/src/components/FormFieldContainer/types.ts
  SharePointFramework/shared-library/src/components/index.ts
  SharePointFramework/shared-library/src/icons/iconCatalog.ts
Labels: enhancement, complexity: medium, frontend

#1283 Mulighet for søk på personer med mer på porteføljeforside
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
Labels: enhancement, complexity: small

#1284 Administrasjon: Ikke mulig å legge til underområder i program. Ved refresh forsvinner de man la til.
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/AddProjectDialog.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/index.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/useAddProjectDialog.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/Commands/Commands.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/Commands/index.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ListHeaderSearch/ListHeaderSearch.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ListHeaderSearch/index.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/ProgramAdministration.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/index.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/types.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/useProgramAdministration.ts
  SharePointFramework/ProgramWebParts/src/data/SPDataAdapter.ts
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/webparts/baseProgramWebPart/index.ts
  SharePointFramework/ProgramWebParts/src/webparts/baseProgramWebPart/types.ts
  SharePointFramework/ProgramWebParts/src/webparts/programAdministration/index.ts
Labels: bug

#1285 Fiks for 2.11 #1267
  SharePointFramework/PortfolioWebParts/src/components/List/ColumnContextMenu/renderMenuItem.tsx
  SharePointFramework/PortfolioWebParts/src/components/List/ListHeader/ListHeader.tsx
  SharePointFramework/PortfolioWebParts/src/components/List/ListHeader/index.ts
  SharePointFramework/PortfolioWebParts/src/components/List/ListHeader/useOnRenderDetailsHeader.tsx
  SharePointFramework/PortfolioWebParts/src/components/List/useList.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnContextMenu/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnContextMenu/useColumnContextMenu.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer/actions.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer/createPortfolioAggregationReducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnContextMenu/ColumnContextMenu.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnContextMenu/index.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ColumnContextMenu/useColumnContextMenu.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverview.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/reducer/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioOverview/index.ts
Labels: bug

#1286 Visuelt løft på prosjektstatus og matriser
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/DynamicMatrix.module.scss
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/MatrixCell.module.scss
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/MatrixElement/MatrixElement.module.scss
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/MatrixElement/index.tsx
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/MatrixHeaderCell/MatrixHeaderCell.module.scss
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/MatrixHeaderCell/index.tsx
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/index.tsx
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixRow/MatrixRow.module.scss
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/useOpportunityMatrix.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/Actions/Actions.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectProperties/ProjectProperty/useProjectProperty.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/ToolbarItems/useToolbarItems.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useCaptureReportSnapshot.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useCommands.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/ProjectStatus.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/ProjectStatus.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/PublishedStatus/PublishedStatus.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/PublishedStatus/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/SectionTabs/SectionTabs.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/SectionTabs/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/BaseSection/BaseSection.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/BaseSection/BaseSection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/ListSection/ListSection.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/ListSection/ListSection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/ProjectPropertiesSection/ProjectPropertiesSection.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/ProjectPropertiesSection/ProjectPropertiesSection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/Sections.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/StatusSection/StatusSection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/SummarySection.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/SummarySection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/UncertaintySection/UncertaintySection.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/UncertaintySection/UncertaintySection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/StatusElement.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/StatusElement.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/StatusElementIcon/StatusElementIcon.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/StatusElementIcon/StatusElementIcon.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/StatusElementIcon/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/UserMessages/UserMessages.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/UserMessages/UserMessages.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/UserMessages/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/TimelineList/TimelineList.module.scss
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/useRiskMatrix.ts
  SharePointFramework/ProjectWebParts/src/loc/_/en-us.js
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/shared-library/src/components/ProjectTimeline/Timeline/ToolbarItems/useToolbarItems.tsx
  SharePointFramework/shared-library/src/components/Toolbar/Toolbar.module.scss
  SharePointFramework/shared-library/src/components/Toolbar/renderMenuButton.tsx
  SharePointFramework/shared-library/src/components/Toolbar/renderToolbarButton.tsx
  SharePointFramework/shared-library/src/icons/iconCatalog.ts
  Templates/Content/Portfolio_content.no-NB/SiteAssets/Konfigurasjon/Risikomatrise/standard-konfigurasjon.json
  Templates/Portfolio/Objects/Lists/Prosjektkolonnekonfigurasjon.xml
  Templates/Portfolio/Objects/Lists/Prosjektkolonner.xml
Labels: enhancement, complexity: large, frontend

#1289 Visuelt løft på dialog for endring av fase
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Actions/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/ChangePhaseDialog.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Content/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/DynamicHomepageContent/DynamicHomepageContent.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/DynamicHomepageContent/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/ChangingPhaseView/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/InitialView.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusActions/StatusActions.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusActions/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusActions/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusOptions/StatusOptions.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusOptions/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusOptions/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/useActions.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/useInitialView.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/CheckListItem.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/SummaryView.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/index.tsx
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/shared-library/src/icons/iconCatalog.ts
Labels: enhancement, complexity: small, frontend

#1290 Visuelt løft og endringer på footer
  SharePointFramework/PortfolioExtensions/.editorconfig
  SharePointFramework/PortfolioExtensions/src/components/Footer/Configuration/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/ConfigurationLink/ConfigurationLink.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/ConfigurationLink/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/HelpContent/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/InstallVersion.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/InstallVersionTooltipContent/InstallVersionTooltipContent.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/InstallVersionTooltipContent/LatestGitHubRelease/LatestGitHubRelease.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/InstallVersionTooltipContent/LatestGitHubRelease/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/InstallVersionTooltipContent/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersion/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/PromotedLinks/PromotedLinks.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/PromotedLinks/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/SiteSettings/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/SiteSettingsLink/SiteSettingsLink.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/SiteSettingsLink/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/index.tsx
  SharePointFramework/PortfolioExtensions/src/extensions/footer/manifest.json
  SharePointFramework/PortfolioExtensions/src/extensions/footer/types.ts
  SharePointFramework/PortfolioExtensions/src/loc/_/en-us.js
  SharePointFramework/PortfolioExtensions/src/loc/myStrings.d.ts
  SharePointFramework/PortfolioExtensions/src/loc/nb-no.js
  SharePointFramework/ProjectExtensions/.editorconfig
  SharePointFramework/shared-library/.editorconfig
  SharePointFramework/shared-library/src/icons/iconCatalog.ts
  Templates/Portfolio/Objects/ClientSidePages/Konfigurasjon.xml
Labels: enhancement, complexity: small, frontend

#1292 Fiks for 3.11 #1267
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Actions/Actions.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Actions/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/ChangePhaseDialog.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Content/Content.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Content/VIEW_MAP.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Content/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Content/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/DynamicHomepageContent/DynamicHomepageContent.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/DynamicHomepageContent/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/ChangingPhaseView/ChangingPhaseView.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/ChangingPhaseView/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/InitialView.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusActions/StatusActions.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/StatusActions/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/CheckListItem.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/CheckListItem/useCheckListItem.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/SummaryView.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/SummaryView/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/context.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/reducer.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/useChangePhaseDialog.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/index.tsx
  SharePointFramework/shared-library/src/models/ChecklistItemModel.ts
Labels: bug
