Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-01, with the labels that each got.

#937 ProjectData fetch bug ProgramTimeline
  SharePointFramework/ProgramWebParts/src/data/index.ts
Labels: bug

#939 Add a height to the helpcontent div styling
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/helpContent/index.tsx
  Templates/JsonTemplates/_JsonTemplateProgram.json
Labels: bug, complexity: small, frontend

#941 Remove wiping of Extensions and ListContent from 'Maloppsett'
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
Labels: bug

#942 Replace 'Gevinstoversikt' at Project level with the new aggregated webpart
  Install/Scripts/EnsureProjectAggregrationWebPart/$.json
  Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
  Install/Scripts/EnsureProjectAggregrationWebPart/Template_ProjectAggregationWebPart.xml
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  SharePointFramework/PortfolioWebParts/config/config.json
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitMeasurementAchievement/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitMeasurementAchievement/types.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitMeasurementsModal/BenefitMeasurementsModal.module.scss
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitMeasurementsModal/columns.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitMeasurementsModal/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/BenefitsOverview.module.scss
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/columns.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/config.ts
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/BenefitsOverview/types.ts
  SharePointFramework/PortfolioWebParts/src/components/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/benefitsOverview/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/benefitsOverview/manifest.json
  SharePointFramework/README.md
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: enhancement, complexity: small, backend

#952 Fixed collapsing groups in aggregated webparts
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
Labels: bug

#954 Added TaxonomyBA to build script
  Install/Build-Release.ps1
Labels: bug
