Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-03, with the labels that each got.

#1040 Updated workflows after changing to release branching
  .development-guide/.README
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-releases.yml
  .github/workflows/ci-temp.yml
  .github/workflows/pr-package-spfx-dev.yml
Labels: ci

#1041 Fikset feil relatert til henting av hubchildren
  CHANGELOG.md
  Install/Scripts/PP365Functions.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
Labels: bug, installation, priority: medium

#1043 Fiks for kommandolinje og standard egenskaper på prosjekttidslinje
  CHANGELOG.md
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/types.ts
  Templates/JsonTemplates/_JsonTemplateProgram.json
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: bug, complexity: small

#1055 SharePoint "Full kontroll" tilgangsnivå rettighetssjekk
  CHANGELOG.md
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
Labels: bug

#1028 Tilgang for å opprette porteføljeoversikt-visninger er nå basert på tilgang til listen
  CHANGELOG.md
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/services/PortalDataService/index.ts
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/types.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/IPortfolioConfiguration.ts
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/types.ts
  releasenotes/1.9.0.md
Labels: enhancement, priority: low, complexity: medium

#1062 Fiks for doble scrollbars på hjelpeinnhold-vindu
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/components/HelpContent/HelpContentModal/HelpContentModal.module.scss
  SharePointFramework/ProjectExtensions/src/components/HelpContent/HelpContentModal/index.tsx
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/useTemplateSelectDialog.ts
Labels: bug

#1063 Porteføljeoversikt: vis personlige visninger som egen "seksjon"
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
Labels: enhancement

#1060 Alfabetisk filtrering på filter-verdier for Ressursallokering
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocation.ts
Labels: enhancement

#1064 Fix for FN's bærekraftsmål missing
  CHANGELOG.md
  Install/Install.ps1
  Install/Scripts/PostInstallUpgrade.ps1
  Install/Scripts/PreInstallUpgrade.ps1
  Templates/Taxonomy/Taxonomy.xml
  Templates/Upgrade/1.8.1/1.8.1.xml
Labels: bug, complexity: small

#1069 Initiell footer for porteføljenivå (v0.1)
  SharePointFramework/PortfolioExtensions/config/config.json
  SharePointFramework/PortfolioExtensions/package.json
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/InstallVersionTooltipContent.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/LatestGitHubRelease/LatestGitHubRelease.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/LatestGitHubRelease/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/LatestGitHubRelease/types.ts
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/LatestGitHubRelease/useLatestGitHubRelease.ts
  SharePointFramework/PortfolioExtensions/src/components/Footer/InstallVersionTooltipContent/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/context.ts
  SharePointFramework/PortfolioExtensions/src/components/Footer/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/types.ts
  SharePointFramework/PortfolioExtensions/src/components/Footer/useFooter.ts
  SharePointFramework/PortfolioExtensions/src/extensions/footer/index.ts
  SharePointFramework/PortfolioExtensions/src/extensions/footer/manifest.json
  SharePointFramework/PortfolioExtensions/src/extensions/footer/types.ts
  SharePointFramework/PortfolioExtensions/src/loc/myStrings.d.ts
  SharePointFramework/PortfolioExtensions/src/loc/nb-no.js
  Templates/Portfolio/Objects/CustomActions.xml
Labels: enhancement, complexity: medium

#1073 CI using node version from repository variables
  .github/workflows/build-release.yml
  .github/workflows/ci-releases.yml
  .github/workflows/pr-package-spfx-dev.yml
Labels: ci

#1074 Lister som finnes på Konfigurasjonssiden gjemmes fra områdeinnhold
  Templates/Portfolio/Objects/ClientSidePages/Konfigurasjon.xml
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
  Templates/Portfolio/Objects/Lists/Prosjektdata.xml
  Templates/Portfolio/Objects/Lists/Prosjekter.xml
  Templates/Portfolio/Objects/Lists/Prosjektstatus.xml
  Templates/Portfolio/Objects/Lists/Tidslinjeinnhold.xml
  Templates/Portfolio/Objects/Lists/Tidslinjekonfigurasjon.xml
Labels: enhancement

#1078 Omskrivning av Porteføljeoversikten til å være en funksjonell komponent
  SharePointFramework/PortfolioWebParts/config/config.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ListHeader/ListHeader.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ListHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/ListHeader/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverview.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/types.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/context.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/useColumnHeaderClick.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/useColumnHeaderContextMenu.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/useFetchData.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/useFilteredData.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/usePersistedColumns.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/usePortfolioOverview.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/usePortfolioOverviewFilters.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocation.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
Labels: enhancement, complexity: medium
