Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-05, with the labels that each got.

#1101 Unngå begrensninger på planneroppgaver + logging
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/package-lock.json
  SharePointFramework/ProjectExtensions/src/loc/myStrings.d.ts
  SharePointFramework/ProjectExtensions/src/loc/nb-no.js
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/types.ts
  Templates/Portfolio/Objects/ContentTypes/Planneroppgave.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
  releasenotes/1.9.0.md
  releasenotes/assets/1.9/planner-begrensninger.png
Labels: bug, enhancement, complexity: small, backend

#1100 Aggregerte oversikter henter ut alle elementer
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/data/index.ts
Labels: bug

#1102 Midlertidig fiks for #1049
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useCommands.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/usePublishReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/UserMessages/UserMessages.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/UserMessages/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/reducer.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/types.ts
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
Labels: bug

#1103 Støtte tooltip-kolonne i porteføljeoversikten
  CHANGELOG.md
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
  SharePointFramework/@Shared/src/models/ProjectColumn.ts
  SharePointFramework/@Shared/src/models/ProjectColumnConfig.ts
  SharePointFramework/@Shared/src/models/SPProjectColumnConfigItem.ts
  SharePointFramework/@Shared/src/services/PortalDataService/index.ts
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TagsColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/UserColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/types.ts
  Templates/Portfolio/Objects/ContentTypes/Prosjektkolonnekonfigurasjonselement.xml
  Templates/Portfolio/Objects/Lists/Prosjektkolonnekonfigurasjon.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/Portfolio/GtPortfolioColumnTooltip.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
  releasenotes/1.9.0.md
  releasenotes/assets/1.9/tooltip-konfigurasjon.png
  releasenotes/assets/1.9/tooltip-oversikt.png
Labels: enhancement

#1109 Endra standardsortering av dokumentbibliotek i prosjekter
  CHANGELOG.md
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: complexity: small, sharepoint-configuration

#1117 "Vis i statusseksjonen" ble ikke overholdt
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/index.tsx
Labels: bug

#1118 Omskriving av forkortelsen evt. til ev.
  Templates/Content/Portfolio_content.no-NB/Portfolio_content.no-NB.xml
  Templates/Content/Portfolio_content_BA.no-NB/Portfolio_content_BA.no-NB.xml
Labels: priority: low, complexity: small

#1122 Fiks for synkronisering dersom prosjektet mangler i den sentrale prosjektlista
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
Labels: enhancement

#1130 Støtte for å "rendre" URL-kolonner i Porteføljeoversikten
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/index.tsx
  SharePointFramework/ProjectWebParts/.hintrc
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectProperties/ProjectProperty/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/ProjectProperties/ProjectProperty/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/index.tsx
Labels: enhancement, complexity: small, frontend

#1136 Låst mal hindrer mulighet for å gjøre et område om til overordnet
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
Labels: bug, complexity: small

#1138 Fiks for program/overordnet visningene i prosjektutlistingswebdelen (rc1.8.2)
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListViews.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
Labels: bug

#1137 Fiks for program/overordnet visningene i prosjektutlistingswebdelen
  .github/workflows/ci-releases.yml
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListViews.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
Labels: bug

#1131 Støtte for manuelle konfigurasjoner i risikomatrise
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/types.tsx
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/useMatrixCell.ts
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/MatrixCell/useMatrixCellColor.ts
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/DynamicMatrix/types.ts
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/useOpportunityMatrixConfiguration.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/types.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/useRiskMatrix.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/useRiskMatrixConfiguration.ts
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
  Templates/Content/Portfolio_content.no-NB/Portfolio_content.no-NB.xml
  Templates/Content/Portfolio_content.no-NB/SiteAssets/Konfigurasjon/risiko-matrise-konfigurasjon.json
Labels: enhancement

#1139 Oversikten for underordnet innhold er fullt opp av innhold før områder er koblet til programmet
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/src/data/IFetchDataForViewItemResult.ts
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/data/types.ts
  SharePointFramework/ProgramWebParts/src/webparts/baseProgramWebPart/index.ts
Labels: bug

#1124 Søk i aggregerte oversikter søker nå også på prosjektnavn
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/config/config.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/search.ts
Labels: enhancement

#1129 Kjøre hooks som siste Task for provisjonering
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/loc/myStrings.d.ts
  SharePointFramework/ProjectExtensions/src/loc/nb-no.js
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ApplyTemplate/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/Hooks/HooksTaskError.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/Hooks/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/index.ts
Labels: enhancement, complexity: small, customer funded

#1141 Mer avansert støtte for manuelle konfigurasjoner for Risikomatrise
  .github/workflows/ci-releases.yml
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/useRiskMatrixConfiguration.ts
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
  SharePointFramework/ProjectWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProjectWebParts/src/loc/nb-no.js
  SharePointFramework/ProjectWebParts/src/types/IConfigurationFile.ts
  SharePointFramework/ProjectWebParts/src/types/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/@baseProjectWebPart/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/types.ts
  SharePointFramework/ProjectWebParts/src/webparts/riskMatrix/index.ts
  SharePointFramework/ProjectWebParts/src/webparts/riskMatrix/types.ts
  Templates/Content/Portfolio_content.no-NB/Portfolio_content.no-NB.xml
  Templates/Content/Portfolio_content.no-NB/SiteAssets/Konfigurasjon/Risikomatrise/standard-konfigurasjon.json
Labels: enhancement

#1142 Lagt til nivå på Datakilder-listen
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/models/DataSource.ts
  SharePointFramework/@Shared/src/services/DataSourceService/index.ts
  SharePointFramework/PortfolioExtensions/package.json
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/usePortfolioAggregation.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TitleColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListViews.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/IAggregatedListConfiguration.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/index.tsx
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
  SharePointFramework/ProgramWebParts/src/webparts/programAggregation/index.tsx
  SharePointFramework/ProgramWebParts/src/webparts/programAggregation/types.ts
  SharePointFramework/ProjectExtensions/package.json
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/Hooks/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/useRiskMatrixConfiguration.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
  Templates/Portfolio/Objects/ContentTypes/Datakilde.xml
  Templates/Portfolio/Objects/Lists/Datakilder.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/DataSource/GtDataSourceLevel.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
Labels: enhancement

#1152 Tving oppsett av prosjektmal dersom låst og satt til å konfigurere automatisk
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/models/ProjectTemplate.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/@BaseTask/BaseTaskError.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/@BaseTask/IBaseTask.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/@BaseTask/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/@BaseTask/types.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ApplyTemplate/ApplyTemplateTaskError.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ApplyTemplate/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ApplyTemplate/types.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/Hooks/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/ProvisionSiteFields/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/SetupProjectInformation/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/SitePermissions/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/types.ts
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
Labels: enhancement, complexity: small
