Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-02, with the labels that each got.

#958 Fornorsking av PP github
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/feil-problem-mangel-i-l-sningen.md
  .github/ISSUE_TEMPLATE/feil.yml
  .github/ISSUE_TEMPLATE/forbedring.yml
  .github/ISSUE_TEMPLATE/forbedringsforslag.md
  .github/ISSUE_TEMPLATE/funksjonalitet.yml
  .github/ISSUE_TEMPLATE/ny-funksjonalitet.md
  .github/ISSUE_TEMPLATE/release-test-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/RELEASE_TEMPLATE.md
Labels: internal

#963 Aggregrert innhold: Støtte for dokumentnavn-kolonne med filtype-ikon
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnContextMenu/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnContextMenu/useColumnContextMenu.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/ColumnFormPanel.module.scss
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/renderOptions.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ColumnFormPanel/useColumnFormPanel.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ItemModal/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/ItemModal/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TitleColumn/types.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/data/IFetchDataForViewItemResult.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/data/types.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/fetchTimelineData.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/data/transformItems.ts
  SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts
  Templates/Portfolio/Objects/SiteFields/GtFieldDataType.xml
Labels: priority: high, search, complexity: medium, frontend

#968 Install and Template changes related to B&A
  Install/Build-Release.ps1
  Install/Scripts/PP365Functions.ps1
  Install/Scripts/PostInstall.ps1
  Install/Scripts/PostInstallUpgrade.ps1
  Install/Scripts/PreInstallUpgrade.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
Labels: bug, installation

#973 Vise alle prosjekter i 'Oversikt' webdel (Prorgam)
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
Labels: enhancement

#975 Skjul tom '? Hjelp tilgjengelig' linje dersom hjelpeinnhold ikke er definert for siden
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/helpContent/index.tsx
Labels: bug

#979 Vise statusrapport ikoner standard i prosjektinformasjon webdel
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/index.tsx
Labels: bug, enhancement

#981 Fikset problem med 'Usikkerhetsoversikt' kategori mangel
  Templates/Portfolio/Objects/Lists/Hjelpeinnhold.xml
  Templates/Portfolio/Objects/Lists/Prosjektinnholdskolonner.xml
Labels: bug

#983 Fikse problem med prosjektutlistingswebdel
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListState.ts
Labels: bug

#982 Vise alle prosjekter i Administrasjon webdel for program #972
  CHANGELOG.md
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/index.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/AddProjectDialog/useAddProjectDialog.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/columns.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/data.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/types.ts
Labels: complexity: medium, customer funded

#993 'Etikett' felt standard i nyopprettede/eksisterende prosjekter
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  Templates/JsonTemplates/_JsonTemplateProgram.json
  Templates/JsonTemplates/_JsonTemplateProject.json
  Templates/Portfolio/Objects/Lists/Tidslinjekonfigurasjon.xml
  Templates/Portfolio/Objects/SiteFields/GtTag.xml
Labels: enhancement

#994 Legge inn støtte for låst Prosjektmal i Prosjektoppsett dialog
  .github/PULL_REQUEST_TEMPLATE.md
  SharePointFramework/ProjectExtensions/package-lock.json
  SharePointFramework/ProjectExtensions/src/components/TemplateSelectDialog/TemplateSelector/index.tsx
  SharePointFramework/ProjectExtensions/src/projectSetup/index.ts
Labels: enhancement

#992 Bugfix: Standard listeinnhold på standardmal ved nyinstallasjon
  Install/Scripts/PostInstall.ps1
  Install/Scripts/PostInstallUpgrade.ps1
Labels: bug

#1001 Fiks for lagring av øyeblikksbilde for prosjektstatus
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformation.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/useProjectPhasesDataFetch.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useCaptureReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/index.tsx
  SharePointFramework/ProjectWebParts/src/webparts/@baseProjectWebPart/index.ts
Labels: bug

#1003 Fikset feil med prosjektutlistings-webdelen hvor gjester kunne se fanen "Alle prosjekter"
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListViews.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
Labels: bug

#1006 Fiks for "Rediger egenskaper" i Prosjektinformasjon-webdelen
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
  SharePointFramework/@Shared/src/interfaces/IHubSite.ts
  SharePointFramework/@Shared/src/logging/ListLogger.ts
  SharePointFramework/@Shared/src/services/PortalDataService/index.ts
  SharePointFramework/@Shared/src/services/ProjectDataService/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformationDataFetch.ts
Labels: bug

#1005 Ikke genere standardplan når planneroppgaver er valgt
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
Labels: bug

#1009 Tidslinje for et programs prosjekter viser ikke lenger informasjonsmelding
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/index.tsx
Labels: priority: medium, complexity: small

#1010 Tittel-kolonnen for aggregert webdel "rendres" som en klikkbar lenke som går til elementet
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
Labels: enhancement, complexity: small, frontend

#1011 Fikset gruppering for aggregerte oversikter
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/usePortfolioAggregation.ts
Labels: bug, complexity: small

#1017 Endring av informasjonsmelding for tidslinje for et programs prosjekter
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/Timeline/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/types.ts
  SharePointFramework/ProgramWebParts/package-lock.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/loc/mystrings.d.ts
  SharePointFramework/ProgramWebParts/src/loc/nb-no.js
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/index.tsx
  SharePointFramework/ProgramWebParts/src/webparts/programTimeline/types.ts
Labels: bug

#1007 Rettet opp i Usikkerhetsmatrisenes standardtekster og akser
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/getMatrixHeaders.ts
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/types.ts
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/useOpportunityMatrix.ts
  SharePointFramework/ProjectWebParts/src/components/OpportunityMatrix/useOpportunityMatrixConfiguration.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/UncertaintySection/index.tsx
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/getMatrixHeaders.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/types.ts
  SharePointFramework/ProjectWebParts/src/webparts/projectStatus/index.ts
Labels: bug, complexity: small

#1022 Rettelse av navigasjonsmeny for prosjekter og programmer
  Templates/JsonTemplates/_JsonTemplateParent.json
  Templates/JsonTemplates/_JsonTemplateProgram.json
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: bug

#1023 Fikset gruppering for programaggreringswebdelen
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAggregation/itemColumn.tsx
  SharePointFramework/ProgramWebParts/src/components/ProgramAggregation/reducer.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAggregation/useProgramAggregation.ts
Labels: bug

#1031 Fiks for #1030
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/StatusElement/useStatusElement.ts
  SharePointFramework/ProjectWebParts/src/components/RiskMatrix/types.ts
Labels: bug

#1034 Håndterer fjerning av ugyldige spesialkarakterer når man genererer øyeblikksbilde for prosjektstatus
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useCaptureReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useDeleteReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useEditFormUrl.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/usePublishReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useRedirectNewStatusReport.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Commands/useReportOptions.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/SummarySection/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/UncertaintySection/useUncertaintySection.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Sections/useCreateContextValue.tsx
Labels: bug, complexity: small

#1032 Retter en feil med visning av prosjektinformasjon-panel
  SharePointFramework/@Shared/package-lock.json
  SharePointFramework/@Shared/package.json
  SharePointFramework/PortfolioWebParts/package-lock.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/itemColumn.tsx
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/usePortfolioAggregation.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/RenderItemColumn/TitleColumn/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/types.ts
  SharePointFramework/PortfolioWebParts/src/webparts/@basePortfolioWebPart/index.ts
  SharePointFramework/ProjectWebParts/package-lock.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/BaseWebPartComponent/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformation.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformationDataFetch.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectStatus/Header/useHeader.ts
Labels: bug

#1036 Release notes
  CHANGELOG.md
  releasenotes/1.8.0.md
  releasenotes/assets/ba-mal.png
  releasenotes/assets/fasesider.png
  releasenotes/assets/fns-baerekraftsmal.png
  releasenotes/assets/logg.png
  releasenotes/assets/mulighetsmatrise.png
  releasenotes/assets/overordnet.png
  releasenotes/assets/prosjektadministrasjonsroller-liste.png
  releasenotes/assets/prosjektadministrasjonsroller.png
  releasenotes/assets/statusrapport-prosjektinfo-1.png
  releasenotes/assets/statusrapport-prosjektinfo-2.png
  releasenotes/assets/statusrapport-prosjektinfo-3.png
  releasenotes/assets/tilgang-til-vertikal.png
  releasenotes/assets/tilgang-til-visning.png
  releasenotes/assets/usikkerhetsmatrise-1.png
  releasenotes/assets/usikkerhetsmatrise-2.png
  releasenotes/assets/usikkerhetsmatrise-3.png
Labels: internal
