Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-04, with the labels that each got.

#1076 Maloppsett og Tidslinjekonfigurasjon gjemmes fra områdeinnhold
  CHANGELOG.md
  Templates/Portfolio/Objects/ClientSidePages/Konfigurasjon.xml
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
  Templates/Portfolio/Objects/Lists/Prosjektdata.xml
  Templates/Portfolio/Objects/Lists/Prosjekter.xml
  Templates/Portfolio/Objects/Lists/Prosjektstatus.xml
  Templates/Portfolio/Objects/Lists/Tidslinjeinnhold.xml
  Templates/Portfolio/Objects/Lists/Tidslinjekonfigurasjon.xml
Labels: enhancement, complexity: small

#1081 Sorteringsrekkefølge på Planner oppgaver
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/models/IPlannerTaskSPItem.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
  Templates/Content/Portfolio_content.no-NB/Portfolio_content.no-NB.xml
  Templates/Portfolio/Objects/Lists/Planneroppgaver.xml
  releasenotes/1.9.0.md
Labels: enhancement, complexity: small, customer funded

#1067 Porteføljeoversikt: vis personlige visninger som egen "seksjon"
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
Labels: enhancement

#1077 "Standard visningsmodus" er nå lagt til som egenskap for prosjektliste-webdelen
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListState.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocation.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/manifest.json
Labels: enhancement, complexity: small

#1084 Etiketter på planneroppgaver
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/package-lock.json
  SharePointFramework/ProjectExtensions/package.json
  SharePointFramework/ProjectExtensions/src/models/IPlannerTaskSPItem.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/CopyListData/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/index.ts
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/PlannerConfiguration/types.ts
  Templates/Portfolio/Objects/ContentTypes/Planneroppgave.xml
  Templates/Portfolio/Objects/Lists/BA/Planneroppgaver Anlegg.xml
  Templates/Portfolio/Objects/Lists/BA/Planneroppgaver Bygg.xml
  Templates/Portfolio/Objects/Lists/Planneroppgaver.xml
  Templates/Portfolio/Objects/SiteFields/@.xml
  Templates/Portfolio/Objects/SiteFields/Planner/GtAttachments.xml
  Templates/Portfolio/Objects/SiteFields/Planner/GtCategory.xml
  Templates/Portfolio/Objects/SiteFields/Planner/GtChecklist.xml
  Templates/Portfolio/Objects/SiteFields/Planner/GtPlannerPreviewType.xml
  Templates/Portfolio/Objects/SiteFields/Planner/GtPlannerTags.xml
  Templates/Portfolio/Resources.en-US.resx
  Templates/Portfolio/Resources.no-NB.resx
  releasenotes/1.8.0.md
  releasenotes/1.9.0.md
  releasenotes/assets/1.8/ba-mal.png
  releasenotes/assets/1.8/fasesider.png
  releasenotes/assets/1.8/fns-baerekraftsmal.png
  releasenotes/assets/1.8/logg.png
  releasenotes/assets/1.8/mulighetsmatrise.png
  releasenotes/assets/1.8/overordnet.png
  releasenotes/assets/1.8/prosjektadministrasjonsroller-liste.png
  releasenotes/assets/1.8/prosjektadministrasjonsroller.png
  releasenotes/assets/1.8/statusrapport-prosjektinfo-1.png
  releasenotes/assets/1.8/statusrapport-prosjektinfo-2.png
  releasenotes/assets/1.8/statusrapport-prosjektinfo-3.png
  releasenotes/assets/1.8/tilgang-til-vertikal.png
  releasenotes/assets/1.8/tilgang-til-visning.png
  releasenotes/assets/1.8/usikkerhetsmatrise-1.png
  releasenotes/assets/1.8/usikkerhetsmatrise-2.png
  releasenotes/assets/1.8/usikkerhetsmatrise-3.png
  releasenotes/assets/1.9/planneroppgaver-etiketter.png
Labels: complexity: medium, backend

#1089 Håndterer deaktiverte/stengte kontoer i kopiering av tillatelseskonfigurasjon
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/projectSetup/tasks/SitePermissions/index.ts
Labels: bug, enhancement

#1088 Fiks for uthenting av prosjektinformasjon for brukere uten tilgang til hubområdet
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/types.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/useProjectInformationDataFetch.ts
Labels: bug

#1093 Changed field type of GtSearchQuery
  CHANGELOG.md
  Templates/Portfolio/Objects/SiteFields/GtSearchQuery.xml
Labels: complexity: small, sharepoint-configuration

#1096 Fiks for Gevinstoversikt på prosjektnivå
  .vscode/settings.json
  CHANGELOG.md
  Install/Scripts/EnsureProjectAggregrationWebPart/$.json
  Install/Scripts/EnsureProjectAggregrationWebPart/JsonControlData_Gevinstoversikt.json
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/PortfolioOverviewCommands/usePortfolioOverviewCommands.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListState.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  Templates/JsonTemplates/_JsonTemplateProject.json
Labels: bug
