Repository Puzzlepart/prosjektportalen365, pull requests merged in 2023-08, with the labels that each got.

#1231 Visuell oppgradering av prosjektutlistingswebdel - Prosjektkort + kommandobar
  CHANGELOG.md
  SharePointFramework/PortfolioExtensions/package.json
  SharePointFramework/PortfolioWebParts/config/package-solution.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCard.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardContent/ProjectCardContent.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardContent/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardContent/useProjectCardContent.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardFooter/ProjectCardFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardFooter/useProjectCardFooter.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/ProjectCardHeader.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/context.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/useProjectCard.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectList.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListVerticals.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/IRenderModeDropdownProps.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/RenderModeDropdown.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectListState.ts
  SharePointFramework/PortfolioWebParts/src/data/index.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/latestProjects/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioAggregation/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioInsights/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/portfolioOverview/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/projectTimeline/manifest.json
  SharePointFramework/PortfolioWebParts/src/webparts/resourceAllocation/manifest.json
  SharePointFramework/ProgramWebParts/package.json
  SharePointFramework/ProgramWebParts/src/data/index.ts
  SharePointFramework/ProjectExtensions/package.json
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/shared-library/package.json
  SharePointFramework/shared-library/src/models/ProjectListModel.ts
  SharePointFramework/shared-library/src/models/SPProjectItem.ts
  Templates/Portfolio/Objects/ClientSidePages/Home.xml
  common/config/rush/pnpm-lock.yaml
  releasenotes/1.9.0.md
Labels: enhancement, complexity: large, frontend

#1236 Visuell oppgradering av prosjektutlistingswebdel - Listevisning
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/List.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/context.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/context.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectList.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListColumns.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/RenderModeDropdown.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/loc/en-us.js
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/manifest.json
Labels: enhancement, complexity: medium, frontend

#1246 Fiks for at noen gjestebrukere har blank e-post og blank loginname i pagecontext brukerobjektet
  CHANGELOG.md
  SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts
Labels: bug

#1243 Visuell oppgradering av "siste prosjekter" webdel
  SharePointFramework/PortfolioWebParts/src/components/LatestProjects/LatestProjects.module.scss
  SharePointFramework/PortfolioWebParts/src/components/LatestProjects/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/LatestProjects/types.ts
  SharePointFramework/PortfolioWebParts/src/components/LatestProjects/useLatestProjects.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioInsights/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/List.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/ProjectCardHeader.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/loc/_/en-us.js
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/latestProjects/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/latestProjects/manifest.json
  SharePointFramework/shared-library/src/components/ProjectLogo/ProjectLogo.module.scss
  SharePointFramework/shared-library/src/components/ProjectLogo/index.tsx
  SharePointFramework/shared-library/src/components/ProjectLogo/types.ts
  SharePointFramework/shared-library/src/components/WebPartTitle/WebPartTitle.module.scss
  SharePointFramework/shared-library/src/components/WebPartTitle/index.tsx
  SharePointFramework/shared-library/src/components/WebPartTitle/types.ts
  SharePointFramework/shared-library/src/components/index.ts
  SharePointFramework/shared-library/src/models/ItemFieldValues.ts
  releasenotes/1.9.0.md
Labels: enhancement, complexity: small, frontend

#1250 Bruk av ProjectLogo komponent for prosjektutlistinswebdel
  SharePointFramework/PortfolioWebParts/src/components/LatestProjects/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/ProjectCardHeader.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/useProjectCardHeader.ts
  SharePointFramework/shared-library/src/components/ProjectLogo/ProjectLogo.module.scss
  SharePointFramework/shared-library/src/components/ProjectLogo/index.tsx
  SharePointFramework/shared-library/src/components/ProjectLogo/types.ts
  SharePointFramework/shared-library/src/components/ProjectLogo/useProjectLogo.ts
  SharePointFramework/shared-library/src/loc/_/en-us.js
  SharePointFramework/shared-library/src/loc/mystrings.d.ts
  SharePointFramework/shared-library/src/loc/nb-no.js
Labels: complexity: medium, backend

#1253 Forbedringer - Prosjektutlisting (dynamisk meny)
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/context.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/useColumns.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/List/useList.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardContent/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardFooter/ProjectCardFooter.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardFooter/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectListColumns.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectMenu/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectMenu/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/RenderModeDropdown/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/projectList/manifest.json
  SharePointFramework/shared-library/src/components/ProjectLogo/index.tsx
Labels: enhancement, complexity: small, frontend

#1259 Refaktorering og visuelle endringer for ressursallokering og tidslinje
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/useProjectList.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/DetailsCallout/DetailsCallout.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/DetailsCallout/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/DetailsCallout/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/ResourceAllocation.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/Timeline.overrides.css
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/groupRenderer.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/itemRenderer.tsx
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/types.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useFilteredData.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocation.ts
  SharePointFramework/PortfolioWebParts/src/components/ResourceAllocation/useResourceAllocationDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/index.ts
  SharePointFramework/PortfolioWebParts/src/interfaces/IAllocationSearchResult.ts
  SharePointFramework/PortfolioWebParts/src/loc/mystrings.d.ts
  SharePointFramework/PortfolioWebParts/src/loc/nb-no.js
  SharePointFramework/PortfolioWebParts/src/webparts/resourceAllocation/index.ts
  SharePointFramework/ProgramWebParts/src/components/ProgramAdministration/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectTimeline/TimelineList/TimelineList.module.scss
  SharePointFramework/shared-library/src/components/ProjectTimeline/DetailsCallout/DetailsCallout.module.scss
  SharePointFramework/shared-library/src/components/ProjectTimeline/DetailsCallout/index.tsx
  SharePointFramework/shared-library/src/components/ProjectTimeline/Timeline/Timeline.module.scss
  SharePointFramework/shared-library/src/components/ProjectTimeline/Timeline/index.tsx
  SharePointFramework/shared-library/src/components/ProjectTimeline/Timeline/useItemRenderer.tsx
  SharePointFramework/shared-library/src/components/ProjectTimeline/index.tsx
  SharePointFramework/shared-library/src/components/WebPartTitle/Tooltip/Tooltip.module.scss
  SharePointFramework/shared-library/src/components/WebPartTitle/Tooltip/index.tsx
  SharePointFramework/shared-library/src/components/WebPartTitle/Tooltip/types.ts
  SharePointFramework/shared-library/src/components/WebPartTitle/WebPartTitle.module.scss
  SharePointFramework/shared-library/src/components/WebPartTitle/index.tsx
  SharePointFramework/shared-library/src/components/WebPartTitle/types.ts
  SharePointFramework/shared-library/src/interfaces/ITimelineItem.ts
  SharePointFramework/shared-library/src/loc/mystrings.d.ts
  SharePointFramework/shared-library/src/loc/nb-no.js
Labels: enhancement
