Repository Puzzlepart/prosjektportalen365, pull requests merged in 2024-04, with the labels that each got.

#1493 Prosjektutlisting forbedringer på ytelse og innlasting
  CHANGELOG.md
  SharePointFramework/PortfolioWebParts/config/config.json
  SharePointFramework/PortfolioWebParts/package.json
  SharePointFramework/PortfolioWebParts/src/components/EditViewColumnsPanel/useSelectableColumns.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectCard/ProjectCardHeader/useProjectCardHeader.ts
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/ProjectList.module.scss
  SharePointFramework/PortfolioWebParts/src/components/ProjectList/index.tsx
  SharePointFramework/shared-library/src/components/ProjectLogo/useProjectLogo.ts
  common/config/rush/pnpm-lock.yaml
Labels: enhancement, complexity: medium, frontend

#1495 Legge til mulighet for konfigurere anbefalingsalternativer og verdier
  CHANGELOG.md
  SharePointFramework/PortfolioExtensions/src/components/IdeaApprovalDialog/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/IdeaApprovalDialog/types.ts
  SharePointFramework/PortfolioExtensions/src/components/IdeaDialog/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/IdeaDialog/types.ts
  SharePointFramework/PortfolioExtensions/src/extensions/ideaProcessing/index.ts
  SharePointFramework/PortfolioExtensions/src/extensions/ideaProjectData/index.tsx
  SharePointFramework/PortfolioExtensions/src/extensions/ideaRegistration/index.tsx
  SharePointFramework/PortfolioExtensions/src/loc/_/en-us.js
  SharePointFramework/PortfolioExtensions/src/loc/myStrings.d.ts
  SharePointFramework/PortfolioExtensions/src/loc/nb-no.js
  SharePointFramework/PortfolioExtensions/src/models/IdeaConfigurationModel.ts
  SharePointFramework/ProjectExtensions/src/components/RiskAction/RiskActionPopover/NewRiskActionPanel/ResponsibleField/ResponsibleField.tsx
  Templates/Portfolio/Objects/Lists/Idea/Idekonfigurasjon.xml
  Templates/Portfolio/Objects/SiteFields/Idea/GtIdeaProcessingChoices.xml
  Templates/Portfolio/Objects/SiteFields/Idea/GtIdeaRegistrationChoices.xml
  common/config/rush/pnpm-lock.yaml
Labels: enhancement, priority: medium, complexity: small, customer funded

#1508 Forbedringer av Install.ps1 og UpgradeAllExistingSitesToLatest.ps1 skriptene
  CHANGELOG.md
  Install/Install.ps1
  Install/Scripts/PostInstall.ps1
  Install/Scripts/UpgradeAllSitesToLatest.ps1
  Install/Scripts/UpgradeAllSitesToLatest/EnsureProjectAggregrationWebPart.ps1
  Install/Scripts/UpgradeAllSitesToLatest/EnsureResourceLoadIsSiteColumn.ps1
  Templates/Portfolio/Objects/Lists/Maloppsett.xml
Labels: bug, enhancement, installation, complexity: small

#1507 Rettet et problem hvor taksonomifelt i redigeringspanel ikke støttet nivåer av termer
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectInformation/EditPropertiesPanel/EditPropertiesPanel.tsx
  SharePointFramework/shared-library/config/config.json
  SharePointFramework/shared-library/package.json
  SharePointFramework/shared-library/src/components/CustomEditPanel/CustomEditPanelBody/FieldElements/TaxonomyFieldType.tsx
  SharePointFramework/shared-library/src/components/CustomEditPanel/CustomEditPanelBody/FieldElements/TaxonomyFieldTypeMulti.tsx
  SharePointFramework/shared-library/src/components/CustomEditPanel/CustomEditPanelBody/FieldElements/useInitialTaxonomyValues.ts
  SharePointFramework/shared-library/src/components/CustomEditPanel/useModel.ts
  SharePointFramework/shared-library/src/services/ProjectDataService/ProjectDataService.ts
  common/config/rush/pnpm-lock.yaml
Labels: bug, complexity: medium

#1509 Rettet et problem hvor "Ansvarlig"-feltet i administrering av tiltak ikke viste personen som er valgt i feltet
  CHANGELOG.md
  SharePointFramework/ProjectExtensions/src/components/RiskAction/RiskActionPopover/NewRiskActionPanel/ResponsibleField/ResponsibleField.tsx
Labels: bug, complexity: small

#1512 Rettet et problem hvor det ikke var mulig å lagre tom verdi i valuta/tall felt fra redigeringspanel
  CHANGELOG.md
  SharePointFramework/shared-library/src/components/CustomEditPanel/CustomEditPanelBody/FieldElements/Currency.tsx
  SharePointFramework/shared-library/src/components/CustomEditPanel/CustomEditPanelBody/FieldElements/Number.tsx
Labels: bug, complexity: small
