Repository Puzzlepart/prosjektportalen365, pull requests merged in 2025-02, with the labels that each got.

#1604 Oversiktsvisning - Idémodul
  CHANGELOG.md
  SharePointFramework/.eslintrc.yaml
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/Commands/useToolbarItems.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/Commands/Commands.module.scss
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/Commands/Commands.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/Commands/index.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/Commands/renderModes.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/Commands/useCommands.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/IdeaList.module.scss
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/IdeaList.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/List.module.scss
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/List.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/context.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/index.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/types.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/useColumns.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/List/useList.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/index.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/types.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/useIdeaList.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaList/useIdeaListRenderer.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaModule.module.scss
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/IdeaModule.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/types.ts
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/useIdeaModule.tsx
  SharePointFramework/PortfolioWebParts/src/components/IdeaModule/useIdeaModuleDataFetch.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/reducer/getInitialState.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/types.ts
  SharePointFramework/PortfolioWebParts/src/components/PortfolioAggregation/useDefaultColumns.tsx
  SharePointFramework/PortfolioWebParts/src/webparts/ideaModule/index.ts
  SharePointFramework/PortfolioWebParts/src/webparts/ideaModule/index.tsx
  Templates/Portfolio/Objects/ClientSidePages/Idemodul.xml
  Templates/Portfolio/Objects/Lists/Datakilder.xml
  Templates/Portfolio/Objects/SiteFields/DataSource/GtDataSourceCategory.xml
Labels: enhancement, frontend

#1605 Automatisk minimering og skjuling av footer
  CHANGELOG.md
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/types.ts
  SharePointFramework/PortfolioExtensions/src/extensions/footer/index.ts
  Templates/Portfolio/Objects/Lists/Globale innstillinger.xml
  Templates/Portfolio/Objects/SiteFields/GtSettingsCategory.xml
Labels: enhancement, frontend

#1606 Prosjektportalen assistent (eksperimentell)
  SharePointFramework/PortfolioExtensions/src/components/Footer/Assistant/Assistant.module.scss
  SharePointFramework/PortfolioExtensions/src/components/Footer/Assistant/Assistant.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/Assistant/index.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/Footer.tsx
  SharePointFramework/PortfolioExtensions/src/components/Footer/types.ts
  SharePointFramework/PortfolioExtensions/src/extensions/footer/index.ts
  SharePointFramework/shared-library/src/icons/iconCatalog.ts
  Templates/Portfolio/Objects/Lists/Globale innstillinger.xml
Labels: enhancement, new feature

#1610 Fikser feil der raske utføringer av fasesjekkpunkter ikke registreres
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/useActions.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/Views/InitialView/useInitialView.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/context.ts
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/useChangePhaseDialog.tsx
Labels: bug

#1615 Egendefinerte farger på faser i fasevelgeren
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/package.json
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/ProjectPhase.module.scss
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/ProjectPhase.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/index.tsx
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ProjectPhase/useProjectPhase.ts
  common/config/rush/pnpm-lock.yaml
Labels: frontend, new feature

#1617 Gjennomgå sjekkpunkter for initiell fase
  CHANGELOG.md
  SharePointFramework/ProjectWebParts/src/components/ProjectPhases/ChangePhaseDialog/reducer.ts
Labels: enhancement, customer funded
